version: '2'
services:

  lms:
    restart: always
    entrypoint: bash -c '/etc/init.d/rsyslog start && /bin/sleep 10 && chown www-data:www-data /edx/var/edxapp/media/grades && chown www-data:www-data /edx/var/edxapp/media/user_tasks && source /edx/app/edxapp/venvs/edxapp/bin/activate && python /edx/app/edxapp/edx-platform/manage.py lms runserver 0.0.0.0:8000 --settings aws'
