---
- name: create xqueue application and auth config
  template:
    src: "{{ configuration_roles_dir }}/xqueue/templates/{{ item.src }}"
    dest: "{{ xqueue_configs_result_path }}/{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'xqueue.env.json.j2', dest: 'xqueue.env.json', mode: '0644' }
    - { src: 'xqueue.auth.json.j2', dest: 'xqueue.auth.json', mode: '0644' }
  tags:
    - "docker:configs"
    - "docker:update_xqueue_configs"