---

EDXAPP_SITE_NAME: 127.0.0.1:18000
EDXAPP_LMS_SITE_NAME: '{{ EDXAPP_SITE_NAME }}'
EDXAPP_CMS_SITE_NAME: 127.0.0.1:18010
EDXAPP_LMS_BASE: '{{ EDXAPP_SITE_NAME }}'
EDXAPP_CMS_BASE: '{{ EDXAPP_CMS_SITE_NAME }}'
EDXAPP_PREVIEW_LMS_BASE: edx.fullstack.preview

#### docker
mysql_host: edx.fullstack.mysql
worker_host: 127.0.0.1
memcached_host: edx.fullstack.memcached
mongo_hosts: edx.fullstack.mongo
elasticsearch_host: edx.fullstack.elasticsearch
rabbit_master: edx.fullstack.rabbitmq
xqueue_host: edx.fullstack.xqueue
certs_host: edx.fullstack.certs
forum_host: edx.fullstack.nginx
#### docker

#Mysql installation Variables
EDXAPP_MYSQL_HOST: '{{ mysql_host }}'
EDXAPP_MYSQL_CSMH_HOST: '{{ mysql_host }}'

#mysql database
EDXAPP_MYSQL_PASSWORD_ADMIN: SOME_SECRET_PASSWORD
EDXAPP_MYSQL_USER_ADMIN: root
EDXAPP_MYSQL_PORT: '3306'
EDXAPP_MYSQL_DB_NAME: edxapp

EDXAPP_MYSQL_CSMH_DB_NAME: 'edxapp_csmh'
XQUEUE_MYSQL_DB_NAME: 'xqueue'
COMMON_MYSQL_MIGRATE_USER: 'migrate'
XQUEUE_MYSQL_USER: 'xqueue'
COMMON_MYSQL_ADMIN_USER: 'admin'

#MongoDB installation variables
EDXAPP_MONGO_HOSTS: '{{ mongo_hosts }}'
EDXAPP_MONGO_DB_NAME: 'edxapp'

MONGO_ADMIN_USER: 'admin'
COMMON_MONGO_READ_ONLY_USER: 'read_only'

mongo_create_users: True

MONGO_BIND_IP: 0.0.0.0
MONGO_MULTITENANT: true

#Elasticserach installation variables
EDXAPP_ELASTIC_SEARCH_HOST: '{{ elasticsearch_host }}'
EDXAPP_ELASTIC_SEARCH_CONFIG:
  - host: '{{ elasticsearch_host }}'
    port: 9200

rabbitmq_ip: '{{ rabbit_master }}'

#xqueue variables
XQUEUE_NGINX_PORT: 18040
XSERVER_NGINX_PORT: 18050
XQUEUE_QUEUES:
  # push queue
  'edX-Open_DemoX': 'http://127.0.0.1:{{ XSERVER_NGINX_PORT }}'
  # pull queues
  'test-pull': !!null
  'certificates': !!null
  'open-ended': !!null
  'open-ended-message': !!null
XQUEUE_LOGGING_ENV: production


XQUEUE_RABBITMQ_USER: 'edx'
XQUEUE_RABBITMQ_HOSTNAME: '{{ rabbit_master }}'
XQUEUE_MYSQL_HOST: '{{ mysql_host }}'

#Certs variables
CERTS_QUEUE_URL: 'http://{{xqueue_host}}:18040'
CERTS_XQUEUE_AUTH_USER: 'edx'
CERTS_XQUEUE_AUTH_PASS: 'edx'
CERTS_QUEUE_USER: 'lms'
CERTS_QUEUE_PASS: '{{ XQUEUE_DJANGO_USERS.lms }}'
CERTS_URL: 'http://{{certs_host}}:18090'
CERTS_DOWNLOAD_URL: 'http://{{certs_host}}:18090'
CERTS_VERIFY_URL: 'http://{{certs_host}}:18090'

#forum variables
FORUM_MONGO_HOSTS: '{{ mongo_hosts }}'
FORUM_MONGO_DATABASE: '{{ MONGO_CS_COMMENTS_SERVICE_DB_NAME }}'
FORUM_SINATRA_ENV: 'production'
FORUM_RACK_ENV: 'production'
FORUM_ELASTICSEARCH_HOST: '{{ elasticsearch_host }}'
FORUM_ELASTICSEARCH_PORT: '9200'
FORUM_MONGO_URL: "mongodb://{{ FORUM_MONGO_USER }}:{{ FORUM_MONGO_PASSWORD }}@{{ mongo_hosts }}:27017/{{ MONGO_CS_COMMENTS_SERVICE_DB_NAME }}"

#edxapp variables
EDXAPP_SESSION_COOKIE_DOMAIN: ''
EDXAPP_COMMENTS_SERVICE_URL: 'http://{{forum_host}}:18080'
EDXAPP_RABBIT_HOSTNAME: '{{ rabbit_master }}'
EDXAPP_XQUEUE_URL: 'http://{{xqueue_host}}:18040'
EDXAPP_OEE_URL: 'http://{{ora_host}}:18040/'
EDXAPP_MEMCACHE: ['{{memcached_host}}:11211']

SANDBOX_ENABLE_ECOMMERCE: false
#------------------------------------------------------------------------------------
EDXAPP_STAFF_PASSWORD: edx

ANALYTICS_API_EMAIL_HOST_PASSWORD: '{{ EDXAPP_EMAIL_HOST_PASSWORD }}'
DISCOVERY_EMAIL_HOST_PASSWORD: '{{ EDXAPP_EMAIL_HOST_PASSWORD }}'
INSIGHTS_EMAIL_HOST_PASSWORD: '{{ EDXAPP_EMAIL_HOST_PASSWORD }}'
NOTIFIER_EMAIL_PASS: '{{ EDXAPP_EMAIL_HOST_PASSWORD }}'

ANALYTICS_PIPELINE_OUTPUT_DATABASE_PASSWORD: SOME_SECRET_PASSWORD
ANALYTICS_SCHEDULE_MASTER_SSH_CREDENTIAL_PASSPHRASE: SOME_SECRET_PASSWORD
COMMON_HTPASSWD_PASS: SOME_SECRET_PASSWORD
COMMON_HTPASSWD_USER: SOME_SECRET_PASSWORD
COMMON_MONGO_READ_ONLY_PASS: SOME_SECRET_PASSWORD
COMMON_MYSQL_ADMIN_PASS: SOME_SECRET_PASSWORD
COMMON_MYSQL_MIGRATE_PASS: SOME_SECRET_PASSWORD
COMMON_MYSQL_READ_ONLY_PASS: SOME_SECRET_PASSWORD
CREDENTIALS_MYSQL_PASSWORD: SOME_SECRET_PASSWORD

FORUM_API_KEY: SOME_SECRET_FORUM_API_KEY
DISCOVERY_MYSQL_PASSWORD: SOME_SECRET_PASSWORD
ECOMMERCE_BROKER_PASSWORD: SOME_SECRET_PASSWORD
ECOMMERCE_DATABASE_PASSWORD: SOME_SECRET_PASSWORD
ECOMMERCE_WORKER_BROKER_PASSWORD: SOME_SECRET_PASSWORD
EDXAPP_CELERY_PASSWORD: SOME_SECRET_PASSWORD
EDXAPP_COMMENTS_SERVICE_KEY: '{{ FORUM_API_KEY }}'
EDXAPP_MYSQL_CSMH_PASSWORD: SOME_SECRET_PASSWORD
EDXAPP_MYSQL_PASSWORD: SOME_SECRET_PASSWORD
EDXAPP_MYSQL_REPLICA_PASSWORD: '{{ EDXAPP_MYSQL_PASSWORD }}'
EDXAPP_MYSQL_REPLICA_USER: '{{ EDXAPP_MYSQL_USER }}'
EDXAPP_MYSQL_PASSWORD_READ_ONLY: SOME_SECRET_PASSWORD
EDXAPP_MYSQL_CSMH_USER: 'edxapp_cmsh001'
FLOWER_BROKER_PASSWORD: SOME_SECRET_PASSWORD
HIVE_METASTORE_DATABASE_PASSWORD: SOME_SECRET_PASSWORD
INSIGHTS_DATABASE_PASSWORD: SOME_SECRET_PASSWORD
JENKINS_ANALYTICS_GITHUB_CREDENTIAL_PASSPHRASE: SOME_SECRET_PASSWORD
JENKINS_ANALYTICS_USER_PASSWORD_PLAIN: SOME_SECRET_PASSWORD
MARIADB_CLUSTER_PASSWORD_ADMIN: SOME_SECRET_PASSWORD
MONGO_ADMIN_PASSWORD: SOME_SECRET_PASSWORD
mongo_admin_password: '{{ MONGO_ADMIN_PASSWORD }}'
NOTIFIER_COMMENT_SERVICE_API_KEY: '{{ FORUM_API_KEY }}'
NOTIFIER_USER_SERVICE_HTTP_AUTH_PASS: SOME_SECRET_PASSWORD
POSTFIX_QUEUE_EXTERNAL_SMTP_PASSWORD: SOME_SECRET_PASSWORD
PROGRAMS_DATABASE_PASSWORD: SOME_SECRET_PASSWORD
REDIS_PASSWORD: SOME_SECRET_PASSWORD
SPLUNKFORWARDER_PASSWORD: SOME_SECRET_PASSWORD
SPLUNK_SMTP_PASSWORD: SOME_SECRET_PASSWORD
SPLUNK_SSL_PASSWORD: SOME_SECRET_PASSWORD
SWIFT_LOG_SYNC_PASSWORD: SOME_SECRET_PASSWORD
XQUEUE_BASIC_AUTH_PASSWORD: SOME_SECRET_PASSWORD
XQUEUE_BASIC_AUTH_USER: xqueue_basic_auth_user
XQUEUE_MYSQL_PASSWORD: SOME_SECRET_PASSWORD
XQUEUE_RABBITMQ_PASS: SOME_SECRET_PASSWORD
XSY_PASSWORD: SOME_SECRET_PASSWORD

EDXAPP_MONGO_PASSWORD: SOME_SECRET_PASSWORD
EDXAPP_MONGO_USER: 'edxapp'

FORUM_MONGO_USER: 'cs_comments_service'
FORUM_MONGO_PASSWORD: SOME_SECRET_PASSWORD

RABBIT_ADMIN_PASSWORD: SOME_SECRET_PASSWORD

XQUEUE_DJANGO_USERS:
  lms: xqueue_basic_auth_user

EDXAPP_XQUEUE_DJANGO_AUTH:
  username: 'lms'
  password: '{{ XQUEUE_DJANGO_USERS.lms }}'


# Secret keys for Django Applicatons
CREDENTIALS_SECRET_KEY: SOME_SECRET
DISCOVERY_SECRET_KEY: SOME_SECRET
ECOMMERCE_SECRET_KEY: SOME_SECRET
EDX_NOTES_API_SECRET_KEY: SOME_SECRET
EDXAPP_EDXAPP_SECRET_KEY: SOME_SECRET
EDXAPP_PROFILE_IMAGE_SECRET_KEY: SOME_SECRET
EDXAPP_EDX_API_KEY: SOME_SECRET_EDXAPP_EDX_API_KEY
NOTIFIER_LMS_SECRET_KEY: "{{ EDXAPP_EDX_API_KEY }}"
NOTIFIER_USER_SERVICE_API_KEY: "{{ EDXAPP_EDX_API_KEY }}"
PROGRAMS_SECRET_KEY: SOME_SECRET

MONGO_CS_COMMENTS_SERVICE_DB_NAME: 'cs_comments_service'

MONGO_USERS:
  - user: '{{ FORUM_MONGO_USER }}'
    password: '{{ FORUM_MONGO_PASSWORD }}'
    database: '{{ MONGO_CS_COMMENTS_SERVICE_DB_NAME }}'
    roles: readWrite
  - user: '{{ EDXAPP_MONGO_USER }}'
    password: '{{ EDXAPP_MONGO_PASSWORD }}'
    database: edxapp
    roles: readWrite

RABBIT_USERS:
  - name: 'rabbit'
    password: '{{ RABBIT_ADMIN_PASSWORD }}'
  - name: 'edx'
    password: '{{ XQUEUE_RABBITMQ_PASS }}'
  - name: 'celery'
    password: '{{ EDXAPP_CELERY_PASSWORD }}'

COMMON_JWT_AUDIENCE: SOME_SECRET_COMMON_JWT_AUDIENCE
EDXAPP_LMS_ROOT_URL: "{{ EDXAPP_LMS_BASE_SCHEME | default('https') }}://{{ EDXAPP_LMS_BASE }}"
COMMON_OAUTH_BASE_URL: "{{ EDXAPP_LMS_ROOT_URL }}"
COMMON_JWT_SECRET_KEY: SOME_SECRET

#------------------------------------------------------------------------------------
NGINX_REDIRECT_TO_HTTPS: false

USE_LETSENCRYPT: "no"

EDXAPP_LMS_NGINX_CLIENT_MAX_BODY_SIZE: 4m
EDXAPP_CMS_NGINX_CLIENT_MAX_BODY_SIZE: 200m

EDXAPP_MYSQL_USER: 'edxapp001'
COMMON_MYSQL_READ_ONLY_USER: 'read_only'

migrate_db: 'yes'

edxapp_cms_gunicorn_port: 8010
edxapp_cms_gunicorn_host: 127.0.0.1
edxapp_lms_gunicorn_port: 8000
edxapp_lms_gunicorn_host: 127.0.0.1
EDXAPP_LMS_NGINX_PORT: 18000
EDXAPP_CMS_NGINX_PORT: 18010

EDXAPP_MEDIA_URL: '/media/'
EDXAPP_MEDIA_ROOT: '/edx/var/edxapp/media/'

EDXAPP_GRADE_STORAGE_TYPE_LOCAL: true
EDXAPP_GRADE_STORAGE_KWARGS:
  location: /edx/var/edxapp/media/grades

EDXAPP_FOOTER_ORGANIZATION_IMAGE: 'images/logo.png'

EDXAPP_PLATFORM_NAME: edx-docker
EDXAPP_LANG: 'en_US.UTF-8'
EDXAPP_LANGUAGE_CODE: 'en'

EDXAPP_TIME_ZONE: 'Europe/Kiev'

COMMON_HOSTNAME: '{{ EDXAPP_SITE_NAME }}'
#-------------------------------------------------------------------
EDXAPP_EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'

EDXAPP_EMAIL_HOST: smtp.email.host
EDXAPP_EMAIL_HOST_USER: email_host_user
EDXAPP_EMAIL_HOST_PASSWORD: SOME_SECRET_PASSWORD
EDXAPP_EMAIL_PORT: 587
EDXAPP_EMAIL_USE_TLS: true

EDXAPP_DEFAULT_FROM_EMAIL: devops@raccoongang.com
EDXAPP_TECH_SUPPORT_EMAIL: '{{ EDXAPP_DEFAULT_FROM_EMAIL }}'
EDXAPP_CONTACT_EMAIL: '{{ EDXAPP_DEFAULT_FROM_EMAIL }}'
EDXAPP_BUGS_EMAIL: '{{ EDXAPP_DEFAULT_FROM_EMAIL }}'
EDXAPP_DEFAULT_FEEDBACK_EMAIL: '{{ EDXAPP_DEFAULT_FROM_EMAIL }}'
EDXAPP_DEFAULT_SERVER_EMAIL: '{{ EDXAPP_DEFAULT_FROM_EMAIL }}'
EDXAPP_BULK_EMAIL_DEFAULT_FROM_EMAIL: '{{ EDXAPP_DEFAULT_FROM_EMAIL }}'
EDXAPP_PAYMENT_SUPPORT_EMAIL: '{{ EDXAPP_DEFAULT_FROM_EMAIL }}'

#-------------------------------------------------------------------

#Notifier
NOTIFIER_LANGUAGE: "{{ EDXAPP_LANGUAGE_CODE }}"
#Notifier

EDXAPP_OAUTH_ENFORCE_SECURE: true

EDXAPP_YOUTUBE_API_KEY: ''

# Enable 'visibility in catalog' functionality
EDXAPP_COURSE_CATALOG_VISIBILITY_PERMISSION: 'see_in_catalog'
EDXAPP_COURSE_ABOUT_VISIBILITY_PERMISSION: 'see_about_page'


EDXAPP_THIRD_PARTY_AUTH_BACKENDS:
- 'social.backends.google.GoogleOAuth2'
- 'social.backends.linkedin.LinkedinOAuth2'
- 'social.backends.facebook.FacebookOAuth2'
- 'social.backends.twitter.TwitterOAuth'
- 'third_party_auth.saml.SAMLAuthBackend'

# If you want disable link on page, just set null
EDXAPP_MKTG_URL_LINK_MAP:
  ABOUT: 'about'
  CONTACT: 'contact'
  FAQ: 'help'
  COURSES: 'courses'
  ROOT: 'root'
  TOS: 'tos'
  HONOR: 'honor'
  PRIVACY: 'privacy'
  PRESS: 'press'
  BLOG: 'blog'
  DONATE: 'donate'
  WHAT_IS_VERIFIED_CERT: 'verified-certificate'
  HOW_IT_WORKS: 'how-to-use'

EDXAPP_CMS_MKTG_URLS:
  TOS: //{{ EDXAPP_SITE_NAME }}/tos

EDXAPP_ENABLE_THIRD_PARTY_AUTH: true

EDXAPP_ENABLE_OAUTH2_PROVIDER: true

EDXAPP_ENABLE_S3_GRADE_DOWNLOADS: true

EDXAPP_FEATURES:
  ENABLE_OAUTH2_PROVIDER: '{{ EDXAPP_ENABLE_OAUTH2_PROVIDER }}'
  ENABLE_MOBILE_REST_API: true
  MAX_ASSET_UPLOAD_FILE_SIZE_IN_MB: 200
  BULK_EMAIL_FROM_DIFFERENT_ADDRESSES: false
  AUTH_USE_OPENID_PROVIDER: true
  CERTIFICATES_ENABLED: true
  ENABLE_DISCUSSION_SERVICE: true
  ENABLE_INSTRUCTOR_ANALYTICS: false
  PREVIEW_LMS_BASE: '{{ EDXAPP_PREVIEW_LMS_BASE }}'
  ENABLE_S3_GRADE_DOWNLOADS: '{{ EDXAPP_ENABLE_S3_GRADE_DOWNLOADS }}'
  ENABLE_MKTG_SITE: '{{ EDXAPP_ENABLE_MKTG_SITE }}'
  AUTOMATIC_AUTH_FOR_TESTING: '{{ EDXAPP_ENABLE_AUTO_AUTH }}'
  ENABLE_THIRD_PARTY_AUTH: '{{ EDXAPP_ENABLE_THIRD_PARTY_AUTH }}'
  ENABLE_VIDEO_UPLOAD_PIPELINE: false
  ENABLE_DISCUSSION_HOME_PANEL: true
  ENABLE_COMBINED_LOGIN_REGISTRATION: true
  ENABLE_CORS_HEADERS: false
  ENABLE_CROSS_DOMAIN_CSRF_COOKIE: false
  ENABLE_COUNTRY_ACCESS: false
  ENABLE_VIDEO_BEACON: false
  ENABLE_ONLOAD_BEACON: false
  ENABLE_EDXNOTES: '{{ EDXAPP_ENABLE_EDXNOTES }}'
  ENABLE_CREDIT_API: '{{ EDXAPP_ENABLE_CREDIT_API }}'
  ENABLE_CREDIT_ELIGIBILITY: '{{ EDXAPP_ENABLE_CREDIT_ELIGIBILITY }}'
  ENABLE_SPECIAL_EXAMS: false
  # ADDITIONAL SETTINGS
  # Enable certificates
  CERTIFICATES_HTML_VIEW: true
  CERTIFICATES_INSTRUCTOR_GENERATION: true
  # end
  # Enable bulk emails
  ENABLE_INSTRUCTOR_EMAIL: true
  REQUIRE_COURSE_EMAIL_AUTH: false
  # end
  # Disable login and registration button when using SSO
  DISABLE_LOGIN_BUTTON: false
  COURSES_ARE_BROWSABLE: true
  # end
  # Enable sysadmin dashboard on LMS
  ENABLE_SYSADMIN_DASHBOARD: false
  # end
  # Course creation settings
  ENABLE_CREATOR_GROUP: false
  DISABLE_COURSE_CREATION: false
  STUDIO_REQUEST_EMAIL: '{{ EDXAPP_DEFAULT_FROM_EMAIL }}'
  # end
  # Studio copyright link
  STUDIO_COPYRIGHT_LINK: '//{{ EDXAPP_LMS_BASE }}'
  # end
  # Studio course licensing
  LICENSING: true
  # end
  # Frakfurt S3 settings, S3_USE_SIGV4: true and S3_HOST: none s3.eu-central-1.amazonaws.com for francfurt
  S3_USE_SIGV4: false
  S3_HOST: null
  #end

EDXAPP_COMPREHENSIVE_THEME_DIR: '/edx/app/edxapp/themes/ginkgo'
EDXAPP_COMPREHENSIVE_THEME_DIRS:  [/edx/app/edxapp/themes]
EDXAPP_DEFAULT_SITE_THEME: 'ginkgo'
EDXAPP_ENABLE_COMPREHENSIVE_THEMING: true

EDXAPP_PLATFORM_TWITTER_ACCOUNT: '${twitter_account}'

EDXAPP_ANALYTICS_DASHBOARD_URL: null


EDXAPP_ENABLE_ADDITIONAL_MIDDLEWARE_CLASSES: false

EDXAPP_LOCALESET_FROM_REQUEST:
  'en': 'en_US.utf8'

MONGODB_LOG:
  - host: '{{ mongo_hosts }}'
    db: 'xlog'
    user: '{{ EDXAPP_MONGO_USER }}'
    password: '{{ EDXAPP_MONGO_PASSWORD }}'

