---
# Ansible managed

CACHES:
    default:
        BACKEND: django.core.cache.backends.memcached.MemcachedCache
        KEY_PREFIX: credentials
        LOCATION:
        - memcache
CREDENTIALS_LMS_BASE_URL: http://edx.fullstack.nginx:18000
CREDENTIALS_SERVICE_USER: credentials_service_user
DATABASES:
    default:
        ATOMIC_REQUESTS: true
        CONN_MAX_AGE: 60
        ENGINE: django.db.backends.mysql
        HOST: edx.fullstack.mysql
        NAME: credentials
        PASSWORD: password
        PORT: '3306'
        USER: credentials001
DATABASE_OPTIONS:
    connect_timeout: 10
EXTRA_APPS: []
FILE_STORAGE_BACKEND:
    DEFAULT_FILE_STORAGE: django.core.files.storage.FileSystemStorage
    MEDIA_ROOT: /edx/var/credentials/media
    MEDIA_URL: /media/
    STATICFILES_STORAGE: django.contrib.staticfiles.storage.ManifestStaticFilesStorage
    STATIC_ROOT: /edx/var/credentials/static
    STATIC_URL: /static/
LANGUAGE_CODE: en_US.UTF-8
OAUTH2_PROVIDER_URL: http://edx.fullstack.nginx:18000/oauth2
ORGANIZATIONS_API_URL: http://edx.fullstack.nginx:18000/api/organizations/v0/
ORGANIZATIONS_AUDIENCE: lms-key
ORGANIZATIONS_SECRET_KEY: lms-secret
PLATFORM_NAME: edx-docker
PROGRAMS_API_URL: http://edx.fullstack.nginx:18140/api/v1/
PROGRAMS_JWT_AUDIENCE: lms-key
PROGRAMS_JWT_SECRET_KEY: lms-secret
SECRET_KEY: SECURE_STRING
SOCIAL_AUTH_EDX_OIDC_ID_TOKEN_DECRYPTION_KEY: secure-credentials-secret
SOCIAL_AUTH_EDX_OIDC_KEY: secure-credentials-client
SOCIAL_AUTH_EDX_OIDC_LOGOUT_URL: http://edx.fullstack.nginx:18140/logout
SOCIAL_AUTH_EDX_OIDC_SECRET: secure-credentials-secret
SOCIAL_AUTH_EDX_OIDC_URL_ROOT: http://edx.fullstack.nginx:18140/oauth2
SOCIAL_AUTH_REDIRECT_IS_HTTPS: false
TIME_ZONE: UTC
USER_API_URL: http://edx.fullstack.nginx:18140/api/user/v1/
USER_JWT_AUDIENCE: lms-key
USER_JWT_SECRET_KEY: lms-secret
